.PHONY: help install dev test test-cov migrate-up migrate-down migration-gen docker-up docker-down docker-build clean

help:
	@echo "Available commands:"
	@echo "  make install        Install Python dependencies"
	@echo "  make dev            Run FastAPI development server with reload"
	@echo "  make test           Run Pytest test suite"
	@echo "  make test-cov       Run Pytest with coverage reporting"
	@echo "  make migrate-up     Apply Alembic database migrations"
	@echo "  make migrate-down   Rollback latest Alembic migration"
	@echo "  make migration-gen  Generate a new autogenerated Alembic migration (msg='...')"
	@echo "  make docker-up      Start application and PostgreSQL via Docker Compose"
	@echo "  make docker-down    Stop Docker Compose containers"
	@echo "  make docker-build   Rebuild Docker containers"
	@echo "  make clean          Clean python cache and temporary files"

install:
	pip install -r requirements.txt

dev:
	uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

test:
	python -m pytest -v

test-cov:
	python -m pytest -v --cov=app --cov-report=term-missing

migrate-up:
	alembic upgrade head

migrate-down:
	alembic downgrade -1

migration-gen:
	alembic revision --autogenerate -m "$(msg)"

docker-up:
	docker compose up -d

docker-down:
	docker compose down

docker-build:
	docker compose up --build -d

clean:
	find . -type d -name "__pycache__" -exec rm -rf {} +
	find . -type f -name "*.pyc" -delete
	find . -type f -name "*.pyo" -delete
	find . -type f -name "*.pyd" -delete
	rm -rf .pytest_cache .coverage htmlcov
