/**
 * Executes the inference path. Until this harness existed, nothing did.
 *
 * `engine.ts`, `gbm.ts` and `features.ts` type-checked, and `ml/test_train.py` covered the Python
 * side, but no test ever called `loadRiskEngine`, walked a tree in JavaScript, or turned a finding
 * into a rupee figure — because doing any of that needs a model artefact, and the real one is
 * blocked behind the data fetch. So the code that decides what a board sees had never run.
 *
 * This harness builds a model artefact by hand, in memory, and drives the real engine through all
 * three of its documented states: `trained`, `absent`, `rejected`. Three things make it more than a
 * smoke test.
 *
 * First, the arithmetic is cross-checked, not self-checked. `refPredict`/`refSigmoid`/`refInterp`
 * below are an independent implementation written from the serialisation format — a recursive walk
 * rather than the iterative one in `gbm.ts`, a guard-free sigmoid rather than the sign-branched one.
 * The parity fixture's expected values come from *those*, so `verifyParity()` passing means two
 * implementations agree, which is the same argument `ml/gbm.py:predict_from_dict` makes on the
 * Python side. A fixture generated by the code under test would prove nothing, and the harness
 * asserts it has teeth by perturbing an expected value and requiring the check to fail.
 *
 * Second, every rejection is exercised. A malformed artefact used to throw inside verification and
 * reject the whole `loadRiskEngine` promise, so a *corrupt* model looked exactly like a *missing*
 * one. Each mutation below asserts the load still resolves, the state is `rejected`, and the detail
 * names the actual fault.
 *
 * Third, nothing is written to `public/model/`. The artefact exists only as a string in this
 * process. An artefact on disk would be loaded by the running app, and a hand-built one carries no
 * information about anything — `data_is_real` is false and the generator string says so, but the
 * safest place for a fake model is nowhere.
 *
 * NOTHING HERE IS A MEASUREMENT. The trees are three hand-written splits. No number this harness
 * prints may be quoted as model performance; it validates arithmetic, plumbing and refusals.
 *
 * Run: node scripts/check-engine.cjs
 */
'use strict';

const { execFileSync } = require('child_process');
const fs = require('fs');
const os = require('os');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const OUT = fs.mkdtempSync(path.join(os.tmpdir(), 'engine-check-'));

let failures = 0;
let checks = 0;

function check(label, condition, detail) {
  checks += 1;
  if (condition) {
    console.log(`  ok   ${label}`);
  } else {
    failures += 1;
    console.log(`  FAIL ${label}${detail === undefined ? '' : ` — ${detail}`}`);
  }
}

function section(title) {
  console.log(`\n${title}`);
}

execFileSync(
  process.execPath,
  [
    path.join(ROOT, 'node_modules', 'typescript', 'bin', 'tsc'),
    '--module', 'commonjs',
    '--target', 'es2020',
    '--moduleResolution', 'node',
    '--strict',
    '--skipLibCheck',
    '--lib', 'es2020,dom',
    '--outDir', OUT,
    // Without an explicit rootDir, a single entry inside src/model makes src/model the inferred
    // root and the output lands flat. Pinning it keeps the emitted layout the same shape as the
    // source tree, and the same shape scripts/check-exports.cjs requires from.
    '--rootDir', path.join(ROOT, 'src'),
    path.join(ROOT, 'src', 'model', 'engine.ts'),
  ],
  { stdio: 'inherit' }
);

const engineMod = require(path.join(OUT, 'model', 'engine.js'));
const gbm = require(path.join(OUT, 'model', 'gbm.js'));
const features = require(path.join(OUT, 'model', 'features.js'));
const {
  loadRiskEngine,
  verifyParity,
  validateModelShape,
  validateParityFixtureShape,
  lossRatioToRiskIndex,
  riskIndexToLossRatio,
  MODEL_SCHEMA_VERSION,
} = engineMod;

const CROSSWALK = fs.readFileSync(
  path.join(ROOT, 'public', 'frameworks', 'crosswalk.json'),
  'utf8'
);
const crosswalkDoc = JSON.parse(CROSSWALK);
const VULN_KEYS = crosswalkDoc.vulnerability_classes.map((c) => c.key);
const EXPLOIT_NAMES = features.exploitFeatureNames(VULN_KEYS);
const SEVERITY_NAMES = features.severityFeatureNames();

const MODEL_URL = '/model/risk-model.json';
const FIXTURE_URL = '/model/parity-fixture.json';
const CROSSWALK_URL = '/frameworks/crosswalk.json';

// --------------------------------------------------------------------------- //
// a fetch that serves a route table, so the real load path runs unmodified
// --------------------------------------------------------------------------- //
/**
 * `loadRiskEngine` and `loadCrosswalk` both call global `fetch`. Stubbing that rather than
 * refactoring them for injection means the harness drives exactly the code the browser runs,
 * including the status/ok handling that decides `absent` from `rejected`.
 */
function installFetch(routes) {
  // Modelled on a real `Response`, headers included. The loader reads `content-type` to corroborate
  // an HTML body, and a stub without headers would crash the very function whose job is to report a
  // fault calmly — the stub has to offer the interface the shipped code is allowed to assume.
  const headers = (map) => ({
    get: (name) => {
      const key = String(name).toLowerCase();
      const hit = Object.keys(map || {}).find((k) => k.toLowerCase() === key);
      return hit === undefined ? null : map[hit];
    },
  });
  global.fetch = async (url) => {
    const route = routes[String(url)];
    if (route === undefined) {
      return {
        ok: false,
        status: 404,
        headers: headers({}),
        text: async () => 'Not Found',
        json: async () => {
          throw new Error('no body');
        },
      };
    }
    if (route.throws) throw new Error(route.throws);
    const status = route.status ?? 200;
    return {
      ok: status >= 200 && status < 300,
      status,
      headers: headers(route.headers ?? { 'content-type': 'application/json' }),
      json: async () => JSON.parse(route.body),
      text: async () => {
        if (route.bodyThrows) throw new Error(route.bodyThrows);
        return route.body;
      },
    };
  };
}

// --------------------------------------------------------------------------- //
// an independent implementation of the exported format
// --------------------------------------------------------------------------- //
/**
 * Written from the serialisation contract, not from `gbm.ts`. Recursive where the shipped code is
 * iterative; no overflow guard on the sigmoid; a linear scan where the shipped calibrator binary
 * searches. The point of the differences is that a shared mistake is less likely.
 */
function refPredict(model, row) {
  let out = model.base_score;
  for (const tree of model.trees) {
    const walk = (node) => {
      if (tree.feature[node] < 0) return tree.value[node];
      const goLeft = row[tree.feature[node]] <= tree.threshold[node];
      return walk(goLeft ? tree.left[node] : tree.right[node]);
    };
    out += model.learning_rate * walk(0);
  }
  return out;
}

function refSigmoid(z) {
  return 1 / (1 + Math.exp(-z));
}

/** numpy.interp, spelled out: clamp outside the knots, linear between them. */
function refInterp(cal, p) {
  const { x, y } = cal;
  if (p <= x[0]) return y[0];
  if (p >= x[x.length - 1]) return y[y.length - 1];
  for (let i = 1; i < x.length; i += 1) {
    if (p <= x[i]) {
      const span = x[i] - x[i - 1];
      if (span === 0) return y[i - 1];
      return y[i - 1] + ((p - x[i - 1]) * (y[i] - y[i - 1])) / span;
    }
  }
  return y[y.length - 1];
}

function maxDelta(a, b) {
  let worst = 0;
  for (let i = 0; i < a.length; i += 1) {
    const d = Math.abs(a[i] - b[i]);
    if (d > worst) worst = d;
  }
  return worst;
}

// --------------------------------------------------------------------------- //
// the fixture artefact — three hand-written splits, in memory, labelled as such
// --------------------------------------------------------------------------- //
/** Leaf padding, spelled the way ml/gbm.py:to_dict spells it: threshold 0.0, unread children. */
function leaf(value) {
  return { feature: -1, threshold: 0, left: 0, right: 0, value };
}

function split(featureIndex, threshold, left, right) {
  return { feature: featureIndex, threshold, left, right, value: 0 };
}

/** Assemble the columnar tree format from a node list, so the fixtures stay readable. */
function tree(nodes) {
  return {
    feature: nodes.map((n) => n.feature),
    threshold: nodes.map((n) => n.threshold),
    left: nodes.map((n) => n.left),
    right: nodes.map((n) => n.right),
    value: nodes.map((n) => n.value),
  };
}

const EXPLOIT_GBM = {
  objective: 'logistic',
  learning_rate: 0.5,
  base_score: -2,
  n_features: EXPLOIT_NAMES.length,
  feature_names: EXPLOIT_NAMES,
  n_trees: 3,
  trees: [
    // epss (column 6) is the first split, so a change in the EPSS column moves the answer.
    tree([split(6, 0.2, 1, 2), leaf(-1.2), leaf(1.5)]),
    // base_score then attackVector=NETWORK: a two-level tree, so traversal has to hop twice.
    tree([split(0, 7, 1, 2), leaf(-0.4), split(10, 0.5, 3, 4), leaf(0.1), leaf(0.9)]),
    // A pure leaf: the degenerate tree the traversal must still handle.
    tree([leaf(0.25)]),
  ],
};

// base_score 0 and learning_rate 1 on the severity side, so leaf values read directly as log10 USD
// and a wrong figure is obvious by inspection rather than only by arithmetic.
const SEVERITY_MEAN_GBM = {
  objective: 'l2',
  learning_rate: 1,
  base_score: 0,
  n_features: SEVERITY_NAMES.length,
  feature_names: SEVERITY_NAMES,
  n_trees: 2,
  trees: [tree([split(1, 1, 1, 2), leaf(3.4), leaf(5.6)]), tree([leaf(0.3)])],
};

// p10 crosses p90 whenever n_data_varieties is 1, which is most findings. Quantile models are
// fitted independently and nothing forces them to be ordered, so score() has to order them; a
// fixture that never crossed would leave that branch untested.
const SEVERITY_P10_GBM = {
  objective: 'quantile',
  learning_rate: 1,
  base_score: 0,
  n_features: SEVERITY_NAMES.length,
  feature_names: SEVERITY_NAMES,
  n_trees: 1,
  trees: [tree([split(2, 0.5, 1, 2), leaf(3), leaf(5.5)])],
};

const SEVERITY_P90_GBM = {
  objective: 'quantile',
  learning_rate: 1,
  base_score: 0,
  n_features: SEVERITY_NAMES.length,
  feature_names: SEVERITY_NAMES,
  n_trees: 1,
  trees: [tree([leaf(5)])],
};

const CALIBRATION = { method: 'isotonic', n_fit: 0, n_knots: 4, x: [0, 0.1, 0.4, 1], y: [0, 0.05, 0.5, 0.95] };

const FIXTURE_NOTE =
  'HARNESS FIXTURE built by scripts/check-engine.cjs. Three hand-written splits. NOT a trained ' +
  'model, NOT fitted to anything, and no figure derived from it is a measurement.';

/**
 * A deep clone every time. The rejection battery mutates what this returns, and the constants above
 * are shared by reference — an in-place `trees[0].left[0] = 0` would corrupt the fixture for every
 * later case, and the self-referential-node case did exactly that until this cloned.
 */
function goodModel() {
  return clone({
    schema_version: MODEL_SCHEMA_VERSION,
    generated_at: '2026-09-02T00:00:00+00:00',
    generator: `scripts/check-engine.cjs — ${FIXTURE_NOTE}`,
    data_is_real: false,
    data_provenance: {
      dataset_card_generated_at: null,
      sources: FIXTURE_NOTE,
      exploitation_question: 'fixture',
      severity_question: 'fixture',
      train_anchor: 'fixture',
      test_anchor: 'fixture',
    },
    exploitation: {
      feature_names: EXPLOIT_NAMES,
      gbm: EXPLOIT_GBM,
      calibration: CALIBRATION,
      metrics: {
        evaluated_on: 'a fixture, so nothing',
        calibration: {
          method: 'isotonic',
          applied: true,
          n_calibration_rows: 0,
          selection_slice: 'fixture',
          brier_identity_selection: 0,
          brier_isotonic_selection: 0,
        },
      },
    },
    severity: {
      feature_names: SEVERITY_NAMES,
      unit: 'log10_usd',
      mean: SEVERITY_MEAN_GBM,
      p10: SEVERITY_P10_GBM,
      p90: SEVERITY_P90_GBM,
      metrics: { evaluated_on: 'a fixture, so nothing', target: 'log10(fixture)' },
    },
    parity_max_abs_delta: {},
  });
}

// --------------------------------------------------------------------------- //
// the parity fixture — expected values from the INDEPENDENT implementation
// --------------------------------------------------------------------------- //
/** Deterministic noise, so a failure is reproducible and a pass is not luck. */
function lcg(seed) {
  let s = seed >>> 0;
  return () => {
    s = (s * 1664525 + 1013904223) >>> 0;
    return s / 4294967296;
  };
}

function buildRows(width, count, shape) {
  const rand = lcg(20260902);
  const rows = [];
  for (let i = 0; i < count; i += 1) {
    const row = new Array(width).fill(0);
    // Small non-zero noise everywhere: an all-zero row would pass even if the traversal read the
    // wrong column, because every wrong column would also be zero.
    for (let j = 0; j < width; j += 1) row[j] = Math.round(rand() * 1000) / 1000;
    shape(row, i);
    rows.push(row);
  }
  return rows;
}

// The shaping drives each fixture row to a specific leaf, so between them the rows visit every
// leaf in every tree. A parity fixture that only ever reached one leaf would agree trivially.
const EX_ROWS = buildRows(EXPLOIT_NAMES.length, 24, (row, i) => {
  row[0] = i % 2 === 0 ? 4.3 : 9.8;        // base_score, either side of 7
  row[6] = (i % 3) * 0.3;                   // epss, either side of 0.2
  row[10] = i % 4 < 2 ? 1 : 0;              // attackVector=NETWORK, either side of 0.5
});

const SV_ROWS = buildRows(SEVERITY_NAMES.length, 24, (row, i) => {
  row[1] = i % 2 === 0 ? 0.4 : 12.4;        // log_data_total, either side of 1
  row[2] = i % 3 === 0 ? 0 : 1;             // n_data_varieties, either side of 0.5
});

function goodFixture() {
  const raw = EX_ROWS.map((r) => refPredict(EXPLOIT_GBM, r));
  const prob = raw.map(refSigmoid);
  // Cloned for the same reason goodModel() is: callers mutate the result to build the malformed
  // cases, and EX_ROWS / EXPLOIT_NAMES are shared module-level constants.
  return clone({
    note:
      `${FIXTURE_NOTE} Expected values are computed by refPredict/refSigmoid/refInterp in the ` +
      'harness, which is a second implementation of the format — so agreement is a cross-check of ' +
      'src/model/gbm.ts, not a restatement of it.',
    exploitation: {
      feature_names: EXPLOIT_NAMES,
      rows: EX_ROWS,
      expected_raw: raw,
      expected_probability: prob,
      expected_calibrated: prob.map((p) => refInterp(CALIBRATION, p)),
    },
    severity: {
      feature_names: SEVERITY_NAMES,
      rows: SV_ROWS,
      expected_log10_mean: SV_ROWS.map((r) => refPredict(SEVERITY_MEAN_GBM, r)),
      expected_log10_p10: SV_ROWS.map((r) => refPredict(SEVERITY_P10_GBM, r)),
      expected_log10_p90: SV_ROWS.map((r) => refPredict(SEVERITY_P90_GBM, r)),
    },
  });
}

/** Deep clone through JSON: the artefact is JSON by definition, so nothing is lost. */
function clone(value) {
  return JSON.parse(JSON.stringify(value));
}

async function load({ model, fixture, crosswalk = CROSSWALK, extra = {}, headers, bodyThrows }) {
  const routes = { [CROSSWALK_URL]: { body: crosswalk }, ...extra };
  // `headers` and `bodyThrows` attach to the artefact routes only: they exist to model a host that
  // mislabels a content type and a transfer that dies mid-body, both of which are about the model.
  const trim = (route) => ({ ...route, ...(headers ? { headers } : {}), ...(bodyThrows ? { bodyThrows } : {}) });
  if (model !== undefined) {
    routes[MODEL_URL] = trim(typeof model === 'string' ? { body: model } : { body: JSON.stringify(model) });
  }
  if (fixture !== undefined) {
    routes[FIXTURE_URL] = trim(typeof fixture === 'string' ? { body: fixture } : { body: JSON.stringify(fixture) });
  }
  installFetch(routes);
  return loadRiskEngine({ modelUrl: MODEL_URL, fixtureUrl: FIXTURE_URL, crosswalkUrl: CROSSWALK_URL });
}

async function main() {
  section('feature vocabulary: the column order both sides agree on');
  const expectedExploitWidth = 10 + 22 + 15 + VULN_KEYS.length + 1;
  check(
    `the exploitation vector is ${expectedExploitWidth} columns (10 numeric, 22 CVSS, 15 ref tags, ${VULN_KEYS.length} classes, 1 unmatched)`,
    EXPLOIT_NAMES.length === expectedExploitWidth,
    `${EXPLOIT_NAMES.length} names`
  );
  check('the severity vector is 69 columns', SEVERITY_NAMES.length === 69, `${SEVERITY_NAMES.length} names`);
  check(
    'no feature name is repeated in either vector',
    new Set(EXPLOIT_NAMES).size === EXPLOIT_NAMES.length &&
      new Set(SEVERITY_NAMES).size === SEVERITY_NAMES.length,
    'a duplicate name would make the name comparison in engine.ts pass on a shifted column'
  );
  check(
    'n_data_varieties sits at severity column 2, where the substitution table says it does',
    SEVERITY_NAMES[2] === 'n_data_varieties' && SEVERITY_NAMES[3] === 'n_assets',
    `${SEVERITY_NAMES[2]} / ${SEVERITY_NAMES[3]}`
  );

  section('gbm.ts: the ensemble arithmetic, against a second implementation');
  const exRawShipped = EX_ROWS.map((r) => gbm.predictRaw(EXPLOIT_GBM, r));
  const exRawRef = EX_ROWS.map((r) => refPredict(EXPLOIT_GBM, r));
  check(
    'the iterative traversal in gbm.ts and a recursive one agree exactly on 24 rows',
    maxDelta(exRawShipped, exRawRef) === 0,
    `max delta ${maxDelta(exRawShipped, exRawRef).toExponential(3)}`
  );
  const svRawShipped = SV_ROWS.map((r) => gbm.predictRaw(SEVERITY_MEAN_GBM, r));
  check(
    'the same holds for the severity mean model',
    maxDelta(svRawShipped, SV_ROWS.map((r) => refPredict(SEVERITY_MEAN_GBM, r))) === 0
  );
  check(
    'between them the fixture rows reach more than one leaf per model',
    new Set(exRawShipped).size > 3 && new Set(svRawShipped).size > 1,
    `${new Set(exRawShipped).size} distinct exploitation scores, ${new Set(svRawShipped).size} severity`
  );
  const sigDelta = maxDelta(exRawShipped.map(gbm.sigmoid), exRawShipped.map(refSigmoid));
  check(
    'the sign-branched sigmoid matches the naive one to 1e-15',
    sigDelta <= 1e-15,
    `max delta ${sigDelta.toExponential(3)}`
  );
  // The branch exists to keep exp() away from overflow. Both limits have to be exact, not close:
  // an Infinity in the denominator would give NaN, and NaN would propagate to a rupee figure.
  check(
    'the overflow guard holds at the extremes',
    gbm.sigmoid(-800) === 0 && gbm.sigmoid(800) === 1 && !Number.isNaN(gbm.sigmoid(-800)),
    `${gbm.sigmoid(-800)} / ${gbm.sigmoid(800)}`
  );
  const calProbes = [-0.5, 0, 0.05, 0.1, 0.25, 0.4, 0.7, 1, 1.5];
  check(
    'the binary-searched calibrator matches a linear scan, including outside the knots',
    maxDelta(
      calProbes.map((p) => gbm.applyCalibration(CALIBRATION, p)),
      calProbes.map((p) => refInterp(CALIBRATION, p))
    ) <= 1e-15
  );
  check(
    'predictRaw refuses a row of the wrong width instead of reading past the end',
    (() => {
      try {
        gbm.predictRaw(EXPLOIT_GBM, [1, 2, 3]);
        return false;
      } catch (err) {
        return /feature count mismatch/.test(err.message);
      }
    })()
  );

  section("state 'trained': the artefact verifies and the engine accepts it");
  const trained = await load({ model: goodModel(), fixture: goodFixture() });
  check('the state is trained', trained.status.state === 'trained', trained.status.state);
  check('the model is exposed for inference', trained.model !== null);
  check(
    'the parity check ran and passed on 24 rows',
    trained.parity !== null && trained.parity.checked && trained.parity.passed && trained.parity.rows === 24,
    trained.parity ? JSON.stringify(trained.parity.failures) : 'no parity report'
  );
  // The two claims are different and worth separating. The tree traversal is the same additions in
  // the same order in both implementations, so it agrees bit for bit and anything else is a bug.
  // The sigmoid cannot: 1/(1+e^-z) and e^z/(1+e^z) are algebraically equal and round differently in
  // the last bit, which is exactly the slack PARITY_TOLERANCE exists to absorb.
  const rawDeltas = trained.parity ? [trained.parity.maxDelta.exploitationRaw, trained.parity.maxDelta.severityMean, trained.parity.maxDelta.severityP10, trained.parity.maxDelta.severityP90] : [1];
  const probDeltas = trained.parity ? [trained.parity.maxDelta.exploitationProbability, trained.parity.maxDelta.exploitationCalibrated] : [1];
  check(
    'tree traversal reproduces the fixture bit for bit',
    Math.max(...rawDeltas) === 0,
    Math.max(...rawDeltas).toExponential(3)
  );
  check(
    'the probability and the calibrated probability agree to one part in 1e15',
    Math.max(...probDeltas) > 0 && Math.max(...probDeltas) <= 1e-15,
    `${Math.max(...probDeltas).toExponential(3)} — a delta of exactly 0 here would mean the harness is comparing gbm.ts against itself`
  );
  // A fixture artefact is the one case where a model loads and still must not be quoted. If this
  // ever reads true for a hand-built model, the honesty banner is reporting a measurement.
  check('dataIsReal is false, copied from the artefact', trained.status.dataIsReal === false);
  check(
    'the trained message says out loud that the artefact came from fixtures',
    /built from FIXTURES/.test(trained.status.message) && /Do not report any of it/.test(trained.status.message),
    trained.status.message.slice(0, 80)
  );
  check(
    'the detail names the tree count, the evaluation set and the parity delta',
    trained.status.detail.some((d) => /3 trees, 66 features/.test(d)) &&
      trained.status.detail.some((d) => /parity max delta/.test(d)),
    trained.status.detail.join(' | ')
  );
  check('the crosswalk loaded alongside it', trained.crosswalk !== null && trained.vulnClasses.length === 18);
  check(
    'the USD rate is a stated assumption, not a hidden constant',
    trained.usdInr === engineMod.USD_INR_ASSUMPTION.rate && typeof engineMod.USD_INR_ASSUMPTION.asOf === 'string',
    String(trained.usdInr)
  );

  section('the parity check has teeth');
  const perturbed = goodFixture();
  perturbed.exploitation.expected_calibrated[7] += 1e-6;
  const teeth = verifyParity(goodModel(), perturbed);
  check(
    'a 1e-6 perturbation in one expected value fails the check',
    !teeth.passed && teeth.failures.some((f) => /exploitationCalibrated differs/.test(f)),
    JSON.stringify(teeth.failures)
  );
  const reordered = goodFixture();
  reordered.severity.feature_names = [...SEVERITY_NAMES].reverse();
  check(
    'a fixture that disagrees with the model on column order fails before the arithmetic',
    verifyParity(goodModel(), reordered).failures.some((f) => /disagree on the severity feature order/.test(f))
  );

  section("state 'absent': no artefact is deployed");
  const absent = await load({});
  check('the state is absent', absent.status.state === 'absent', absent.status.state);
  check('no model is exposed', absent.model === null && absent.parity === null);
  check(
    'the message points at the three scripts that produce one',
    /No trained model is present/.test(absent.status.message) &&
      /ml\/fetch_real_data\.py/.test(absent.status.message),
    absent.status.message.slice(0, 60)
  );
  check(
    'the detail records what the fetch actually returned, so "absent" is evidenced',
    absent.status.detail.some((d) => /HTTP 404/.test(d)),
    absent.status.detail.join(' | ')
  );
  check(
    'score() returns null rather than a number it cannot justify',
    absent.score(
      { cve_id: 'CVE-2024-0001', vulnerability_name: 'x', description: 'x', cvss_score: 9.8, epss_score: 0.5, actively_exploited: true },
      { asset_type: 'Database', estimated_asset_value_inr: 10000000 },
      new Date('2026-01-01T00:00:00Z')
    ) === null
  );
  check('coverage reports nothing scoreable without a model', absent.coverage([{}, {}]).scoreable === 0);
  // A dev server that is not running throws rather than answering 404. Both mean "not deployed",
  // and neither may be reported as a fault in the artefact.
  installFetch({ [CROSSWALK_URL]: { body: CROSSWALK }, [MODEL_URL]: { throws: 'ECONNREFUSED' } });
  const refused = await loadRiskEngine({ modelUrl: MODEL_URL, fixtureUrl: FIXTURE_URL, crosswalkUrl: CROSSWALK_URL });
  check(
    'a network error is absent, not rejected, and says why',
    refused.status.state === 'absent' && refused.status.detail.some((d) => /ECONNREFUSED/.test(d)),
    `${refused.status.state}: ${refused.status.detail.join(' | ')}`
  );

  /**
   * The single-page-app rewrite, which is how "absent" actually presents in a browser.
   *
   * Every static host answers a path it cannot resolve with index.html at HTTP 200 — vite dev and
   * preview both do, as do GitHub Pages, Netlify, Vercel and an S3 website endpoint. So the fetch
   * for an undeployed model succeeds and returns the app's own shell. Observed in the running app,
   * the banner then read "Model file found but rejected — ... is not valid JSON (Unexpected token
   * '<', "<!DOCTYPE "…)", both halves of which are false: nothing was found and nothing was judged.
   *
   * This is the deployed state of this project until training data lands, so it is the state a judge
   * is most likely to see. Note the previous case in the rejected battery served this very body.
   */
  section("state 'absent': an SPA host serves index.html for a path that does not exist");
  const shells = [
    ['a doctype shell', '<!doctype html><html><head><title>CyberRisk</title></head></html>'],
    ['an uppercase DOCTYPE with leading blank lines', '\n\n  <!DOCTYPE HTML>\n<html lang="en"></html>'],
    ['a shell that opens with an HTML comment', '<!-- built by vite --><html><body></body></html>'],
    ['a bare <html> with no doctype', '<html><head><script src="/src/main.tsx"></script></head></html>'],
    ['an XHTML shell', '<?xml version="1.0"?><html xmlns="http://www.w3.org/1999/xhtml"></html>'],
    ['a shell behind a wrapper element', '<div id="root"></div>\n<html><head></head></html>'],
    ['a BOM before the doctype', '﻿<!doctype html><html></html>'],
    ['an object store XML error document', '<Error><Code>NoSuchKey</Code></Error>'],
  ];
  for (const [label, body] of shells) {
    const served = await load({ model: body, headers: { 'content-type': 'text/html; charset=utf-8' } });
    check(
      `${label} is reported absent, not rejected`,
      served.status.state === 'absent',
      `state=${served.status.state} — a headline saying a model was FOUND when none is deployed is the one thing this banner exists to prevent`
    );
    check(
      `${label} explains the 200, so "absent" is evidenced rather than assumed`,
      served.status.detail.some((d) => /returned markup, not JSON/.test(d) && /index\.html at HTTP 200/.test(d)),
      served.status.detail.join(' | ')
    );
    check(
      `${label} leaves nothing quotable behind`,
      served.model === null && served.parity === null && served.status.dataIsReal === false
    );
  }
  const shellDetail = (await load({ model: shells[0][1], headers: { 'content-type': 'text/html' } }))
    .status.detail.join(' | ');
  check(
    'the served Content-Type is quoted as corroboration',
    /Content-Type: text\/html/.test(shellDetail),
    shellDetail
  );
  // The body decides, never the header. A host that mislabels a good artefact must not cost the
  // model, and a host that labels its shell application/json must not be believed — both directions
  // are asserted, because a header-driven implementation would pass one and fail the other.
  const mislabelled = await load({ model: goodModel(), fixture: goodFixture(), headers: { 'content-type': 'text/html' } });
  check(
    'a valid artefact mislabelled text/html still loads — the body decides, not the header',
    mislabelled.status.state === 'trained',
    `state=${mislabelled.status.state}`
  );
  const shellAsJson = await load({ model: shells[0][1], headers: { 'content-type': 'application/json' } });
  check(
    'a shell labelled application/json is still absent — the body decides there too',
    shellAsJson.status.state === 'absent',
    `state=${shellAsJson.status.state}`
  );
  // A BOM is a byte-order mark, not content, and JSON.parse throws on one. A Windows editor can add
  // it to a perfectly good artefact, so it must not read as corruption.
  const bomModel = await load({ model: '﻿' + JSON.stringify(goodModel()), fixture: goodFixture() });
  check(
    'a BOM ahead of a valid artefact is stripped rather than reported as corruption',
    bomModel.status.state === 'trained',
    `state=${bomModel.status.state}: ${bomModel.status.detail.join(' | ')}`
  );
  // Zero bytes is the opposite conclusion: something wrote that path and stopped. That is a fault in
  // the artefact, so it stays rejected rather than being folded into "not deployed".
  const emptyBody = await load({ model: '' });
  check(
    'an empty body is rejected, not absent — a 0-byte file was written by something',
    emptyBody.status.state === 'rejected' && emptyBody.status.detail.some((d) => /is empty \(0 bytes/.test(d)),
    `state=${emptyBody.status.state}: ${emptyBody.status.detail.join(' | ')}`
  );
  const truncatedTransfer = await load({ model: goodModel(), bodyThrows: 'aborted mid-body' });
  check(
    'a body that cannot be read is absent, not rejected — the transfer failed, the artefact did not',
    truncatedTransfer.status.state === 'absent' &&
      truncatedTransfer.status.detail.some((d) => /body could not be read/.test(d)),
    `state=${truncatedTransfer.status.state}: ${truncatedTransfer.status.detail.join(' | ')}`
  );
  // The crosswalk has the identical exposure and a worse failure: its throw aborts the engine load,
  // so an unhelpful parse error would be the whole of what the operator sees.
  installFetch({ [CROSSWALK_URL]: { body: '<!doctype html><html></html>', headers: { 'content-type': 'text/html' } } });
  let crosswalkErr = null;
  try {
    await loadRiskEngine({ modelUrl: MODEL_URL, fixtureUrl: FIXTURE_URL, crosswalkUrl: CROSSWALK_URL });
  } catch (err) {
    crosswalkErr = err.message;
  }
  check(
    'an undeployed crosswalk says it was not served, not "Unexpected token <"',
    crosswalkErr !== null &&
      /returned markup, not JSON/.test(crosswalkErr) &&
      !/Unexpected token/.test(crosswalkErr),
    String(crosswalkErr)
  );

  section("state 'rejected': every way an artefact can be wrong, and what it says about it");
  /**
   * `model`/`fixture` override the served body; `mutate` edits a clone of the good one. A raw string
   * is served verbatim, which is how the not-JSON cases are expressed.
   */
  const rejections = [
    // Was `'<!doctype html><title>404</title>'`, which is exactly the body a single-page-app host
    // returns for a path that does not exist — so this case was asserting the bug that section
    // below now covers, and it passed for the wrong reason. A truncated artefact is the real
    // unparseable-but-deployed case: those bytes were written by something that meant to write JSON.
    { label: 'a body that is served but is not JSON at all', model: '{"schema_version": 1, "explo', needle: /is served but is not valid JSON/ },
    { label: 'a JSON array where an object belongs', model: '[]', needle: /did not parse to a JSON object/ },
    { label: 'a schema version this bundle does not read', mutate: (m) => { m.schema_version = 99; }, needle: /schema_version is 99/ },
    { label: 'an artefact that states no provenance', mutate: (m) => { delete m.data_is_real; }, needle: /states no provenance/ },
    { label: 'an artefact with no build date', mutate: (m) => { delete m.generated_at; }, needle: /cannot be dated/ },
    { label: 'a missing exploitation section (this used to throw)', mutate: (m) => { delete m.exploitation; }, needle: /exploitation is missing/ },
    { label: 'a missing ensemble (this used to throw)', mutate: (m) => { delete m.exploitation.gbm; }, needle: /exploitation\.gbm is missing/ },
    { label: 'a child index outside the node array', mutate: (m) => { m.exploitation.gbm.trees[1].left[0] = 99; }, needle: /left child 99, outside \[0,5\)/ },
    { label: 'a split on a feature the model does not have', mutate: (m) => { m.exploitation.gbm.trees[0].feature[0] = 4000; }, needle: /beyond the 66 declared/ },
    { label: 'a node that is its own child', mutate: (m) => { m.exploitation.gbm.trees[0].left[0] = 0; }, needle: /is its own left child/ },
    { label: 'a tree with no leaf to terminate on', mutate: (m) => { m.exploitation.gbm.trees[2].feature[0] = 1; }, needle: /has no leaf/ },
    { label: 'ragged node arrays', mutate: (m) => { m.exploitation.gbm.trees[0].value = [0.1]; }, needle: /ragged node arrays/ },
    { label: 'a NaN leaf value, which would score as NaN in silence', mutate: (m) => { m.exploitation.gbm.trees[0].value[1] = null; }, needle: /non-finite value/ },
    { label: 'a non-finite base score', mutate: (m) => { m.severity.mean.base_score = 'nine'; }, needle: /severity\.mean\.base_score is not a finite number/ },
    { label: 'a declared tree count that disagrees with the trees', mutate: (m) => { m.exploitation.gbm.n_trees = 7; }, needle: /n_trees says 7 but 3 trees are present/ },
    { label: 'an exploitation model fitted on the wrong objective', mutate: (m) => { m.exploitation.gbm.objective = 'l2'; }, needle: /exploitation\.gbm\.objective is "l2"/ },
    { label: 'a quantile head that is not a quantile model', mutate: (m) => { m.severity.p10.objective = 'l2'; }, needle: /severity\.p10\.objective/ },
    { label: 'a severity unit the engine does not exponentiate', mutate: (m) => { m.severity.unit = 'usd'; }, needle: /severity\.unit is "usd"/ },
    { label: 'calibration knots that are not sorted', mutate: (m) => { m.exploitation.calibration.x = [0, 0.4, 0.1, 1]; }, needle: /not non-decreasing at knot 2/ },
    { label: 'a calibrated probability above 1', mutate: (m) => { m.exploitation.calibration.y = [0, 0.05, 1.4, 0.95]; }, needle: /outside \[0,1\]/ },
    { label: 'calibration knots that do not pair up', mutate: (m) => { m.exploitation.calibration.y = [0, 1]; }, needle: /4 x knots and 2 y knots/ },
    { label: 'missing metrics (this used to throw when the banner read them)', mutate: (m) => { delete m.exploitation.metrics; }, needle: /exploitation\.metrics is missing/ },
    { label: 'a renamed feature column', mutate: (m) => { m.exploitation.feature_names[6] = 'epss_score'; m.exploitation.gbm.feature_names[6] = 'epss_score'; }, needle: /column 6 is "epss" here but "epss_score" in the model/ },
    { label: 'a fixture that is not deployed', fixture: null, needle: /cannot prove it reproduces the evaluated model/ },
    { label: 'a fixture that is not JSON', fixture: 'not json', needle: /is served but is not valid JSON/ },
    { label: 'a fixture with no rows', fixture: (f) => { f.severity.rows = []; }, needle: /nothing to reproduce/ },
    { label: 'a fixture row of the wrong width', fixture: (f) => { f.exploitation.rows[3] = [1, 2, 3]; }, needle: /rows\[3\] has 3 values, expected 66/ },
    { label: 'a fixture whose expectations outnumber its rows', fixture: (f) => { f.severity.expected_log10_mean.push(1); }, needle: /reads as a parity failure rather than as the malformed fixture it is/ },
    { label: 'a fixture the arithmetic does not reproduce', fixture: (f) => { f.severity.expected_log10_p90[2] = 9; }, needle: /severityP90 differs from the training run by/ },
  ];

  let inferenceLeaked = 0;
  for (const case_ of rejections) {
    const args = {};
    if (case_.model !== undefined) args.model = case_.model;
    else {
      const m = goodModel();
      if (case_.mutate) case_.mutate(m);
      args.model = m;
    }
    if (case_.fixture === null) {
      // Serve no fixture route at all: a 404, which is what a missing file looks like.
    } else if (typeof case_.fixture === 'string') {
      args.fixture = case_.fixture;
    } else {
      const f = goodFixture();
      if (typeof case_.fixture === 'function') case_.fixture(f);
      args.fixture = f;
    }

    let engine;
    try {
      engine = await load(args);
    } catch (err) {
      check(`rejects ${case_.label}`, false, `loadRiskEngine threw instead of resolving: ${err.message}`);
      continue;
    }
    const detail = engine.status.detail.join(' | ');
    check(
      `rejects ${case_.label}`,
      engine.status.state === 'rejected' && case_.needle.test(detail),
      `state=${engine.status.state} detail=${detail.slice(0, 160)}`
    );
    if (engine.model !== null) inferenceLeaked += 1;
  }

  check(
    'no rejected artefact is ever exposed for inference',
    inferenceLeaked === 0,
    `${inferenceLeaked} of ${rejections.length} rejections still handed the model to score()`
  );

  // The one throw that validation deliberately cannot pre-empt: a fixture whose own shape is
  // internally consistent but narrower than the model, so predictRaw raises rather than returning.
  // Before the try/catch this rejected the whole promise and the caller rendered no engine at all,
  // which is the failure that looked identical to no model being deployed.
  const narrowFixture = goodFixture();
  narrowFixture.exploitation.feature_names = EXPLOIT_NAMES.slice(0, 65);
  narrowFixture.exploitation.rows = EX_ROWS.map((r) => r.slice(0, 65));
  const threw = await load({ model: goodModel(), fixture: narrowFixture });
  check(
    'a verification that throws becomes a rejection carrying the message, not a rejected promise',
    threw.status.state === 'rejected' &&
      /verification threw rather than returning a verdict/.test(threw.status.detail.join(' ')) &&
      /feature count mismatch/.test(threw.status.detail.join(' ')),
    threw.status.detail.join(' | ').slice(0, 200)
  );
  check('and it leaves nothing behind to score with', threw.model === null && threw.parity === null);
  check(
    'a rejection explains why rejecting is the right behaviour, not just that it happened',
    /would still produce numbers/.test(threw.status.message),
    threw.status.message.slice(0, 60)
  );

  section('validateModelShape reports every fault at once, not just the first');
  const manyFaults = goodModel();
  manyFaults.schema_version = 3;
  delete manyFaults.data_is_real;
  manyFaults.severity.unit = 'inr';
  manyFaults.exploitation.calibration.y = [0, 0.05, 2, 0.95];
  const found = validateModelShape(manyFaults);
  check(
    'four independent faults produce four complaints',
    found.length === 4,
    `${found.length}: ${found.join(' | ')}`
  );
  check('a good artefact produces none', validateModelShape(goodModel()).length === 0, validateModelShape(goodModel()).join(' | '));
  check('a good fixture produces none', validateParityFixtureShape(goodFixture()).length === 0);
  check(
    'the tree walk stops complaining after four faults rather than printing thousands',
    (() => {
      const corrupt = goodModel();
      for (const t of corrupt.exploitation.gbm.trees) t.left[0] = 500;
      const problems = validateModelShape(corrupt);
      return problems.length <= 5 && problems.some((p) => /outside \[0,/.test(p));
    })()
  );

  section('score(): a finding becomes a probability, a loss band and a rupee figure');
  const scan = JSON.parse(fs.readFileSync(path.join(ROOT, 'public', 'sample-scan.json'), 'utf8'));
  const scanDate = new Date('2026-08-28T00:00:00Z');
  const assetById = new Map(scan.assets.map((a) => [a.asset_id, a]));
  const engine = trained;

  // What the bundled scan can actually be scored on, stated rather than assumed. Zero findings in
  // it carry enrichment.cvss_vector: ml/enrich_scan.py exists and its selftest is green, but it has
  // never been run against the bundled scan because data/raw/ is empty, so there is no NVD corpus to
  // fill the vectors from. The exploitation head is therefore unreachable from real scan data today
  // and this harness is the only thing that runs it. That is a gap, and asserting it means the gap
  // closes loudly rather than silently.
  const kevCount = scan.findings.filter((f) => f.actively_exploited).length;
  const vectorCount = scan.findings.filter((f) => (f.enrichment || {}).cvss_vector).length;
  check(
    `the bundled scan has ${scan.findings.length} findings, ${kevCount} in KEV and ${vectorCount} with a CVSS vector`,
    vectorCount === 0,
    'if this ever fails, enrich_scan.py has started supplying vectors and the assertion below is stale'
  );
  const scoredFromScan = scan.findings.map((f) =>
    engine.score(f, assetById.get(f.asset_id), scanDate)
  );
  check(
    'every non-KEV finding scores null, because 24 of 66 columns would have to be invented',
    scan.findings.every((f, i) => (f.actively_exploited ? scoredFromScan[i] !== null : scoredFromScan[i] === null))
  );
  check(
    `all ${kevCount} KEV findings score by observation, none by prediction`,
    scoredFromScan.filter(Boolean).every((s) => s.probabilityBasis === 'observed_kev' && s.exploitProbability === 1)
  );
  check(
    'an observed probability carries no raw score, so the UI cannot present it as model output',
    scoredFromScan.filter(Boolean).every((s) => s.rawScore === null && s.uncalibratedProbability === null)
  );
  check(
    'coverage() agrees with what score() actually managed',
    engine.coverage(scan.findings).scoreable === kevCount &&
      engine.coverage(scan.findings).total === scan.findings.length,
    JSON.stringify(engine.coverage(scan.findings))
  );

  section('score(): the model path, with a CVSS vector supplied');
  const VECTOR = 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H';
  check('the vector parses, so the finding is scoreable', features.canScoreExploitation({ cvss_vector: VECTOR }));
  const base = scan.findings.find((f) => !f.actively_exploited);
  const asset = assetById.get(base.asset_id);
  const finding = { ...base, enrichment: { cvss_vector: VECTOR, cwe_ids: ['CWE-89'] } };
  const s = engine.score(finding, asset, scanDate);
  check('it now scores', s !== null);

  // Rebuild the rows independently and push them through the reference implementation. This is the
  // end-to-end claim: the number on screen is the ensemble applied to the columns the feature
  // builder produced, and nothing in between has rescaled or reordered anything.
  const exRow = features.buildExploitationRow(
    {
      cvss_score: finding.cvss_score,
      epss_score: finding.epss_score,
      vulnerability_name: finding.vulnerability_name,
      description: finding.description,
      enrichment: finding.enrichment,
      asOf: scanDate,
    },
    engine.vulnClasses,
    engine.cweIndex
  );
  const svRow = features.buildSeverityRow({
    vulnClassKey: exRow.classification.key,
    assetType: asset.asset_type,
    recordsAtRisk: asset.records_at_risk,
    incidentYear: scanDate.getUTCFullYear(),
    org: engine.org,
  });
  const expRaw = refPredict(EXPLOIT_GBM, exRow.row);
  const expProb = refInterp(CALIBRATION, refSigmoid(expRaw));
  check('the basis is model, on a 365-day horizon', s.probabilityBasis === 'model' && s.probabilityHorizonDays === 365);
  check('the raw score is the ensemble applied to the built row', s.rawScore === expRaw, `${s.rawScore} vs ${expRaw}`);
  check(
    'the uncalibrated probability is the sigmoid of it',
    Math.abs(s.uncalibratedProbability - gbm.sigmoid(s.rawScore)) === 0
  );
  check(
    'the reported probability is the calibrated one, and calibration moved it',
    Math.abs(s.exploitProbability - expProb) <= 1e-15 && s.exploitProbability !== s.uncalibratedProbability,
    `${s.exploitProbability} vs ${expProb}, uncalibrated ${s.uncalibratedProbability}`
  );
  check('the probability is a probability', s.exploitProbability >= 0 && s.exploitProbability <= 1);
  const expMean = 10 ** refPredict(SEVERITY_MEAN_GBM, svRow.row);
  check('the dollar loss is 10 to the power of the severity output', Math.abs(s.lossUsd.mean - expMean) <= 1e-9, `${s.lossUsd.mean} vs ${expMean}`);
  check('rupees are dollars times the stated rate', s.lossInr.mean === s.lossUsd.mean * engine.usdInr);
  check('expected annual loss is probability times loss, on all three points of the band',
    s.eal.mean === s.exploitProbability * s.lossInr.mean &&
    s.eal.p10 === s.exploitProbability * s.lossInr.p10 &&
    s.eal.p90 === s.exploitProbability * s.lossInr.p90);
  check('the risk index is the loss-ratio restatement of the EAL', s.riskIndex === lossRatioToRiskIndex(s.eal.mean, asset.estimated_asset_value_inr));
  // The fixture's quantile heads cross whenever n_data_varieties is 1 — which is this finding. An
  // unordered band would print as a negative-width interval on a board report.
  const p10Raw = refPredict(SEVERITY_P10_GBM, svRow.row);
  const p90Raw = refPredict(SEVERITY_P90_GBM, svRow.row);
  check('the fixture quantile heads really do cross here', p10Raw > p90Raw, `p10 ${p10Raw} p90 ${p90Raw}`);
  check('score() orders them anyway, so the band is never negative-width', s.lossUsd.p10 <= s.lossUsd.p90 && s.lossInr.p10 <= s.lossInr.p90 && s.eal.p10 <= s.eal.p90);
  check(
    'the provenance says the vector was observed and names what was not',
    s.exploitProvenance.observed.some((o) => /CVSS base sub-vectors/.test(o)) &&
      s.exploitProvenance.completeness > 0.5 &&
      s.severityProvenance.notes.some((n) => /data varieties/.test(n)),
    `completeness ${s.exploitProvenance.completeness.toFixed(2)}`
  );

  section('score(): the loss is capped at what there is to lose');
  const small = { asset_type: asset.asset_type, estimated_asset_value_inr: 50000 };
  const capped = engine.score(finding, small, scanDate);
  check('the cap is flagged', capped.lossCappedAtAssetValue === true);
  check('no point of the band exceeds the asset value', capped.lossInr.p90 === 50000 && capped.lossInr.mean === 50000);
  check('so the expected loss cannot exceed it either', capped.eal.p90 <= 50000);
  check(
    'and a capped finding is not silently identical to an uncapped one',
    capped.eal.mean < s.eal.mean,
    `${capped.eal.mean} vs ${s.eal.mean}`
  );
  const roomy = engine.score(finding, { asset_type: asset.asset_type, estimated_asset_value_inr: 5e11 }, scanDate);
  check('an asset worth more than the p90 loss is not flagged as capped', roomy.lossCappedAtAssetValue === false);

  section('a KEV finding with a vector is still an observation, not a prediction');
  const kev = scan.findings.find((f) => f.actively_exploited);
  const kevScored = engine.score({ ...kev, enrichment: { cvss_vector: VECTOR } }, assetById.get(kev.asset_id), scanDate);
  check(
    'probability 1, basis observed_kev, and no raw score even though one could have been computed',
    kevScored.exploitProbability === 1 && kevScored.probabilityBasis === 'observed_kev' && kevScored.rawScore === null,
    `${kevScored.exploitProbability} / ${kevScored.probabilityBasis} / ${kevScored.rawScore}`
  );
  check('but it still gets a severity band, so its EAL is the full loss', kevScored.eal.mean === kevScored.lossInr.mean);

  section('withAssumptions(): a restated assumption rescores, it does not re-verify');
  // Both of these were unreachable inputs until now: `loadRiskEngine({ org, usdInr })` existed and
  // nothing ever passed either, so SECTOR_OPTIONS and EMPLOYEE_BANDS were exported and consumed
  // nowhere while two comments in engine.ts claimed both were editable in the UI.
  const bankOrg = { employeeBand: '1001 to 10000', naics2: '52', sectorLabel: 'Finance and insurance' };
  const rebound = engine.withAssumptions({ org: bankOrg });
  check(
    'the new engine carries the new profile and the old one is untouched',
    rebound.org.naics2 === '52' && engine.org.naics2 === features.DEFAULT_ORG_PROFILE.naics2,
    `${rebound.org.naics2} / ${engine.org.naics2}`
  );
  // The identity checks are the point of the whole method. A re-verification here would either
  // re-check the same fixture and report it as fresh evidence, or lose a verified model to a network
  // blip mid-session — so the verdict objects must be the very ones the load produced.
  check(
    'status, parity and the model artefact are the SAME objects, so nothing was re-fetched or re-verified',
    rebound.status === engine.status && rebound.parity === engine.parity && rebound.model === engine.model
  );
  check(
    'the crosswalk and CWE index are shared too, not reloaded',
    rebound.crosswalk === engine.crosswalk && rebound.cweIndex === engine.cweIndex
  );

  const reboundScore = rebound.score(finding, asset, scanDate);
  const bankRow = features.buildSeverityRow({
    vulnClassKey: exRow.classification.key,
    assetType: asset.asset_type,
    recordsAtRisk: asset.records_at_risk,
    incidentYear: scanDate.getUTCFullYear(),
    org: bankOrg,
  });
  check(
    'the severity row really did change, and only in the two org columns',
    (() => {
      const diff = svRow.row
        .map((v, i) => (v === bankRow.row[i] ? null : SEVERITY_NAMES[i]))
        .filter(Boolean);
      // employees= is one-hot plus an ordinal index column, naics= is one-hot plus an `other` flag.
      return (
        diff.length > 0 && diff.every((n) => /^employees=|^naics=|^employee_band_ordinal$/.test(n))
      );
    })(),
    svRow.row.map((v, i) => (v === bankRow.row[i] ? null : SEVERITY_NAMES[i])).filter(Boolean).join(', ')
  );
  check(
    'the dollar loss follows the new comparison set',
    Math.abs(reboundScore.lossUsd.mean - 10 ** refPredict(SEVERITY_MEAN_GBM, bankRow.row)) <= 1e-9,
    `${reboundScore.lossUsd.mean} vs ${10 ** refPredict(SEVERITY_MEAN_GBM, bankRow.row)}`
  );
  // The org profile is a severity input only. If it ever moved the exploitation probability, the two
  // heads would have been wired together and the 365-day KEV-entry claim would no longer hold.
  check(
    'the exploitation probability is untouched by the profile — it is not a severity input',
    reboundScore.exploitProbability === s.exploitProbability &&
      reboundScore.rawScore === s.rawScore
  );
  check(
    'the profile now reports as stated rather than as the platform default',
    rebound.org.employeeBand !== 'Unknown' && rebound.org.naics2 !== ''
  );

  const doubled = engine.withAssumptions({ usdInr: engine.usdInr * 2 });
  const doubledScore = doubled.score(finding, { asset_type: asset.asset_type, estimated_asset_value_inr: 5e11 }, scanDate);
  check(
    'doubling the rate doubles every rupee point of the band, uncapped',
    doubledScore.lossInr.mean === roomy.lossInr.mean * 2 &&
      doubledScore.lossInr.p10 === roomy.lossInr.p10 * 2 &&
      doubledScore.lossInr.p90 === roomy.lossInr.p90 * 2
  );
  check(
    'and leaves the dollar figure and the probability alone',
    doubledScore.lossUsd.mean === roomy.lossUsd.mean &&
      doubledScore.exploitProbability === roomy.exploitProbability
  );
  check(
    'the risk index moves with it, because the EAL did',
    doubledScore.riskIndex >= roomy.riskIndex && doubledScore.eal.mean === roomy.eal.mean * 2
  );
  // A NaN or zero rate would print a screen of ₹0, which reads as "no exposure" rather than as bad
  // input. Ignoring it keeps the last good rate, which is the one the banner and the exports state.
  for (const bad of [0, -85, NaN, Infinity]) {
    const guarded = engine.withAssumptions({ usdInr: bad });
    check(`a rate of ${String(bad)} is ignored, keeping ${engine.usdInr}`, guarded.usdInr === engine.usdInr, String(guarded.usdInr));
  }
  check(
    'an empty change is a no-op that still returns a working engine',
    (() => {
      const same = engine.withAssumptions({});
      return same.org === engine.org && same.usdInr === engine.usdInr && same.score(finding, asset, scanDate) !== null;
    })()
  );
  check(
    'changes compose: profile then rate, both retained',
    (() => {
      const both = engine.withAssumptions({ org: bankOrg }).withAssumptions({ usdInr: 90 });
      return both.org.naics2 === '52' && both.usdInr === 90 && both.status === engine.status;
    })()
  );
  // Out-of-vocabulary values must not produce an all-zero one-hot: the tree would then take a branch
  // no training row ever took. buildSeverityRow maps them onto naics=other and employees=Unknown,
  // which are real training categories.
  check(
    'an unrecognised sector or band lands on the trained fallback column, not on nothing',
    (() => {
      const junk = features.buildSeverityRow({
        vulnClassKey: exRow.classification.key,
        assetType: asset.asset_type,
        recordsAtRisk: asset.records_at_risk,
        incidentYear: scanDate.getUTCFullYear(),
        org: { employeeBand: 'Nine staff', naics2: '99', sectorLabel: 'Invented' },
      });
      const oneHot = (prefix) =>
        SEVERITY_NAMES.reduce((acc, n, i) => (n.startsWith(prefix) ? acc + junk.row[i] : acc), 0);
      const named = (n) => junk.row[SEVERITY_NAMES.indexOf(n)];
      return oneHot('employees=') === 1 && named('employees=Unknown') === 1 && oneHot('naics=') === 1 && named('naics=other') === 1;
    })(),
    'expected exactly one employees= and one naics= column set, on the Unknown/other fallbacks'
  );
  check(
    'an engine with no model still exposes withAssumptions and still refuses to score',
    (() => {
      const reboundAbsent = absent.withAssumptions({ org: bankOrg, usdInr: 90 });
      return (
        reboundAbsent.org.naics2 === '52' &&
        reboundAbsent.usdInr === 90 &&
        reboundAbsent.status === absent.status &&
        reboundAbsent.score(finding, asset, scanDate) === null
      );
    })()
  );

  section('the risk index is a loss ratio, not an opinion');
  const V = 4e8;
  // The two anchors are the whole definition: 0.01% of asset value reads 0, 10% reads 100, log
  // scale between. Anything that drifts here silently rescales every number on every screen.
  check('0.01% of asset value is index 0', Math.abs(lossRatioToRiskIndex(V * 0.0001, V)) < 1e-9, String(lossRatioToRiskIndex(V * 0.0001, V)));
  check('10% of asset value is index 100', Math.abs(lossRatioToRiskIndex(V * 0.1, V) - 100) < 1e-9, String(lossRatioToRiskIndex(V * 0.1, V)));
  // Three decades between the anchors, so each decade of loss is worth 33.3 index points and the
  // geometric midpoint is 0.316% of asset value, not 0.1%. Stating the decade steps rather than one
  // midpoint pins the scale down: a floor or ceiling change would move all three at once.
  check(
    'each decade of loss is a third of the scale: 0.1% is 33, 1% is 67, 0.316% is the midpoint 50',
    lossRatioToRiskIndex(V * 0.001, V) === 33 &&
      lossRatioToRiskIndex(V * 0.01, V) === 67 &&
      lossRatioToRiskIndex(V * 10 ** -2.5, V) === 50,
    `${lossRatioToRiskIndex(V * 0.001, V)} / ${lossRatioToRiskIndex(V * 0.01, V)} / ${lossRatioToRiskIndex(V * 10 ** -2.5, V)}`
  );
  check('below the floor clamps to 0 rather than going negative', lossRatioToRiskIndex(1, V) === 0 && lossRatioToRiskIndex(0, V) === 0);
  check('above the ceiling clamps to 100', lossRatioToRiskIndex(V, V) === 100 && lossRatioToRiskIndex(V * 5, V) === 100);
  // The index is rounded to a whole number for display, so the honest property is non-decreasing
  // plus full traversal of the scale — asserting strict monotonicity would be asserting a bug.
  check(
    'it never decreases as loss rises, and covers the whole 0..100 scale',
    (() => {
      let prev = -1;
      const seen = new Set();
      for (let e = -4.5; e <= -0.5; e += 0.01) {
        const v = lossRatioToRiskIndex(V * 10 ** e, V);
        if (v < prev) return false;
        if (!Number.isInteger(v)) return false;
        prev = v;
        seen.add(v);
      }
      return seen.has(0) && seen.has(100) && seen.size === 101;
    })(),
    'expected every integer from 0 to 100 to be reachable, none skipped and none out of order'
  );
  check(
    'it is scale-free: the same ratio on a 1000x asset gives the same index',
    lossRatioToRiskIndex(V * 0.003, V) === lossRatioToRiskIndex(V * 1000 * 0.003, V * 1000)
  );
  check(
    'riskIndexToLossRatio inverts it at every integer on the scale',
    Array.from({ length: 101 }, (_, i) => i).every(
      (idx) => lossRatioToRiskIndex(riskIndexToLossRatio(idx) * V, V) === idx
    )
  );
  // A zero-value asset is a data-entry reality, not a hypothetical. Division by it must not reach a
  // rupee figure as NaN, which is the same failure class the artefact validator exists to stop.
  check(
    'a zero or absent asset value yields a finite index, not NaN',
    Number.isFinite(lossRatioToRiskIndex(1e6, 0)) && Number.isFinite(lossRatioToRiskIndex(0, 0)),
    `${lossRatioToRiskIndex(1e6, 0)} / ${lossRatioToRiskIndex(0, 0)}`
  );

  section('SEVERITY_COLUMN_SUBSTITUTIONS: the stated domain is the domain served');
  // features.ts documents each substituted column with a domain, and its doc comment says this
  // harness asserts the served rows respect it. Until now that sentence was a promise. A column
  // that drifts outside its training domain is the train/serve skew of task #14 recurring: nothing
  // throws, the tree just takes a branch it was never fitted on.
  const subs = features.SEVERITY_COLUMN_SUBSTITUTIONS;
  check(`the table documents ${subs.length} substituted columns`, subs.length >= 3, `${subs.length}`);
  check(
    'every documented index is a real severity column and the name matches',
    subs.every((c) => SEVERITY_NAMES[c.index] === c.name),
    subs.map((c) => `${c.index}:${c.name} vs ${SEVERITY_NAMES[c.index]}`).join(' | ')
  );
  check(
    'every entry states its training meaning, its browser substitute, why it is defensible, and a domain',
    subs.every(
      (c) =>
        c.training && c.browser && c.reason && Array.isArray(c.domain) && c.domain.length === 2 && c.domain[0] <= c.domain[1]
    )
  );
  // Every finding in the bundled scan against every asset type it appears on, plus the two
  // classification outcomes (resolved by CWE, and unresolved) so both mapping branches are covered.
  const domainRows = [];
  for (const f of scan.findings) {
    const a = assetById.get(f.asset_id);
    for (const enr of [{ cvss_vector: VECTOR, cwe_ids: ['CWE-89'] }, { cvss_vector: VECTOR }, {}]) {
      const cls = features.buildExploitationRow(
        { cvss_score: f.cvss_score, epss_score: f.epss_score, vulnerability_name: f.vulnerability_name, description: f.description, enrichment: enr, asOf: scanDate },
        engine.vulnClasses,
        engine.cweIndex
      ).classification;
      domainRows.push(
        features.buildSeverityRow({
          vulnClassKey: cls.key,
          assetType: a.asset_type,
          recordsAtRisk: a.records_at_risk,
          incidentYear: scanDate.getUTCFullYear(),
          org: engine.org,
        }).row
      );
    }
  }
  check(`${domainRows.length} severity rows built from the bundled scan`, domainRows.length === scan.findings.length * 3);
  const violations = [];
  for (const c of subs) {
    for (const row of domainRows) {
      const v = row[c.index];
      if (!Number.isFinite(v) || v < c.domain[0] || v > c.domain[1]) {
        violations.push(`${c.name}=${v} outside [${c.domain[0]},${c.domain[1]}]`);
        break;
      }
    }
  }
  check('no substituted column leaves its documented domain', violations.length === 0, violations.join(' | '));
  check(
    'and no severity column anywhere is non-finite',
    domainRows.every((r) => r.length === SEVERITY_NAMES.length && r.every(Number.isFinite))
  );
  // The one-hot blocks must stay one-hot: two set bits in the asset-kind block would double-count a
  // coefficient the model fitted on exactly one.
  const kindStart = 6 + 3 + 7;
  check(
    'the asset-kind block is exactly one bit set on every row, including the "other" fallback',
    domainRows.every((r) => r.slice(kindStart, kindStart + 9).reduce((x, y) => x + y, 0) === 1),
    'asset types in the scan: ' + [...new Set(scan.assets.map((a) => a.asset_type))].join(', ')
  );

}

main().then(() => {
  console.log(`\n${checks - failures}/${checks} checks passed`);
  console.log(
    'Note: the model artefact in this harness is three hand-written splits, held in memory and ' +
      'never written to public/model/. It validates arithmetic, plumbing and refusals. No number ' +
      'here is model performance.'
  );
  process.exit(failures === 0 ? 0 : 1);
});




