"""Financial Distribution Histogram ORM model (Phase 6).

Stores pre-computed histogram bins and frequencies generated by Monte Carlo simulations.
"""
from datetime import datetime, timezone
from typing import TYPE_CHECKING, Any, Dict, List
import uuid

from sqlalchemy import DateTime, ForeignKey, Index, JSON, func
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base, GUID

if TYPE_CHECKING:
    from app.models.financial_assessment import FinancialAssessment


class FinancialDistribution(Base):
    """Histogram bucket distribution of Monte Carlo simulated losses."""
    __tablename__ = "financial_distributions"

    id: Mapped[uuid.UUID] = mapped_column(
        GUID,
        primary_key=True,
        default=uuid.uuid4,
        index=True,
    )
    financial_assessment_id: Mapped[uuid.UUID] = mapped_column(
        GUID,
        ForeignKey("financial_assessments.id", ondelete="CASCADE"),
        unique=True,
        nullable=False,
        index=True,
    )

    # Histogram data
    bins: Mapped[List[float]] = mapped_column(
        JSON().with_variant(JSONB(), "postgresql"),
        nullable=False,
    )
    frequencies: Mapped[List[int]] = mapped_column(
        JSON().with_variant(JSONB(), "postgresql"),
        nullable=False,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        server_default=func.now(),
        nullable=False,
    )

    # Relationship
    financial_assessment: Mapped["FinancialAssessment"] = relationship(
        "FinancialAssessment",
        back_populates="distribution",
        lazy="select",
    )

    def __repr__(self) -> str:
        return f"<FinancialDistribution(assessment_id={self.financial_assessment_id}, bins_count={len(self.bins)})>"
